R2009b:
	mex -g -f ./mexopts.R2009b.sh -v zachrect.cpp rect.F
	mex -g -f ./mexopts.R2009b.sh -v -o grid_sepeli sepeli.cpp sepeli_eng.F
	mv *.mex* ../private
R2009a:
	mex -g -f ./mexopts.R2009a.sh -v zachrect.cpp rect.F
	mex -g -f ./mexopts.R2009a.sh -v -o grid_sepeli sepeli.cpp sepeli_eng.F
	mv *.mex* ../private
R2008b:
	mex -g -f ./mexopts.R2008b.sh -v zachrect.cpp rect.F
	mex -g -f ./mexopts.R2008b.sh -v -o grid_sepeli sepeli.cpp sepeli_eng.F
	mv *.mex* ../private
R2007b:
	mex -g -f ./mexopts.R2007b.sh -v zachrect.cpp rect.F
	mex -g -f ./mexopts.R2007b.sh -v -o grid_sepeli sepeli.cpp sepeli_eng.F
	mv *.mex* ../private

