@echo off
rem C:\Documents and Settings\Rich\Application Data\MathWorks\MATLAB\R13\mexopts.bat
rem Generated by gnumex.m script in c:\gnumex-1.11\gnumex-1.11
rem gnumex version: 1.11
rem Compile and link options used for building MEX etc files with
rem the Mingw/Cygwin tools.  Options here are:
rem Cygwin (cygwin*.dll) linking       
rem Mex (*.dll) creation               
rem Safe linking to temporary libraries
rem Language: Fortran                  
rem Compiling for pentium and above    
rem Matlab version 6.5
rem
set MATLAB=C:\MATLAB~1
set GM_PERLPATH=C:\MATLAB~1\sys\perl\win32\bin\perl.exe
set GM_UTIL_PATH=c:\gnumex-1.11\gnumex-1.11
set PATH=C:\cygwin\bin;%PATH%
rem
rem Added libraries for linking
set GM_ADD_LIBS=-lg2c
rem
rem Type of file to compile (mex or engine)
set GM_MEXTYPE=mex
rem
rem Language for compilation
set GM_MEXLANG=f
rem
rem def files to be converted to libs
set GM_DEFS2LINK=libmx.def;libmex.def;libmat.def;_libmatlbmx.def;
rem
rem dlltool command line
set GM_DLLTOOL=c:\gnumex-1.11\gnumex-1.11\mexdlltool -E --as C:\cygwin\bin\as.exe
rem
rem compiler options; add compiler flags to compflags as desired
set NAME_OBJECT=-o
set COMPILER=gcc
set COMPFLAGS=-c -DMATLAB_MEX_FILE -mrtd -fcase-upper -fno-underscoring -fleading-underscore 
set OPTIMFLAGS=-O3 -malign-double -fno-exceptions -mcpu=pentium
set DEBUGFLAGS=-g
rem
rem NB Library creation commands occur in linker scripts
rem
rem Linker parameters
set LINKER=%GM_PERLPATH% %GM_UTIL_PATH%\linkmex.pl
set LINKFLAGS=
set LINKOPTIMFLAGS=-s
set LINKDEBUGFLAGS=-g  -Wl,--image-base,0x28000000\n
set LINK_FILE=
set LINK_LIB=
set NAME_OUTPUT=-o %OUTDIR%%MEX_NAME%.dll
rem
rem Resource compiler parameters
set RC_COMPILER=%GM_PERLPATH% %GM_UTIL_PATH%\rccompile.pl --unix -o %OUTDIR%mexversion.res
set RC_LINKER=
