function help_orthogonality(self)

%    The orthogonality of the current grid is available
% for display through the "View/Orthogonality" menu item.
% The orthogonality is here defined as the maximum deviation
% from 90 degrees of the angles that surround each grid-point,
% Ignoring the corner-points.  To hide the display, select
% the "View/Orthogonality" again.
%    The orthogonality will appear better for smaller grid cells,
% since the calculations are based on straight lines.  Also,
% the orthogonality is better for grids generated by Mex-files.

% Copyright (C) 1999 Dr. Charles R. Denham, ZYDECO.
%  All Rights Reserved.
%   Disclosure without explicit written consent from the
%    copyright owner does not constitute publication.
 
% Version of 25-May-1999 16:27:20.
% Updated    23-Dec-1999 09:47:23.

seagrid_helpdlg(help(mfilename), 'SeaGrid Orthogonality')
